/*
 * generated by Xtext
 */
package famix.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class M3xUiModule extends famix.ui.AbstractM3xUiModule {
	public M3xUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
