/**
 * generated by Xtext
 */
package famix.ui.contentassist;

import famix.ui.contentassist.AbstractM3xProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class M3xProposalProvider extends AbstractM3xProposalProvider {
}
